### ISSUE TITLE
Feature request: Change units of the duration

### ISSUE THREAD

**Issue by nck974** [koaning/pytest-duration-insights#8]
I'm not sure if this is still being maintained. In case it is I would like to propose to make the units of the time somehow configurable. 

In my test scenario I have most of the tests ranging from some seconds up to a few minutes. Having everything in `ms` makes it kind of hard to read:
Example:
![image](https://github.com/koaning/pytest-duration-insights/assets/18548911/2852ca34-1b58-44f4-9bbf-b121319f7e5d)

It would be nice to have something to configure a specific unit or have something dynamic that when it reaches some value it switches to a higher unit.

**Comment by koaning** [comment]
This project is not actively maintained, but if you're willing to help out I think this could be a nice feature to add. There are a bunch of details to get right though. 

Would you want all the milliseconds to update to seconds on the page? Or would it perhaps be fine to add some underscores so that numbers look like `87_123ms`? 

It really has been a while since I touched this repo ... I think the most scary part will be to check if the svelte/npm stuff still works.

**Comment by nck974** [comment]
Being able to see seconds or minutes would be better, but I think just the underscores would also be enough to differentiate the tests that take noticeably longer.

**Comment by nck974** [comment]
Hello, I have never used `svelt` so I may have made a mistake. I tried to implement this feature and at least running the local implementation it looks as follows:
![image](https://github.com/koaning/pytest-duration-insights/assets/18548911/3c62aa67-88a8-49c6-a40e-acfe40d606cc)

**Comment by koaning** [comment]
That looks pretty good to my eye, will have a look!

**Comment by nck974** [comment]
Thank you for the review and creating the new version. I just tested it with my project and using pip version `0.1.2` and works perfectly.
